services:
  - type: web
    name: steel-mixing-optimizer
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn steel_mixing_optimizer_v4.3_authenticated:server
    envVars:
      - key: PRODUCTION
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
